config/routes.rb
Rails.application.routes.draw do
  resources :patients
  root 'patients#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates :first_name, :last_name, :diagnosis, :born_on, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :diagnosis, :born_on)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HospitalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :diagnosis, style: "display: block" %>
    <%= form.text_field :diagnosis %>
  </div>

  <div>
    <%= form.label :born_on, style: "display: block" %>
    <%= form.datetime_field :born_on %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>">
  <p>
    <strong>First name:</strong>
    <%= patient.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= patient.last_name %>
  </p>

  <p>
    <strong>Diagnosis:</strong>
    <%= patient.diagnosis %>
  </p>

  <p>
    <strong>Born on:</strong>
    <%= patient.born_on %>
  </p>

</div>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Show this patient", @patient %> |
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Patients</h1>

<div id="patients">
  <% @patients.each do |patient| %>
    <%= render patient %>
    <p>
      <%= link_to "Show this patient", patient %>
    </p>
    <%= link_to 'Delete Patient', patient_path(patient),
      data: { turbo_method: :delete, 
      turbo_confirm: "Are you sure you want to delete #{patient.first_name} #{patient.last_name}" 
      }
      %>
  <% end %>
</div>

<%= link_to "New patient", new_patient_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @patient %>

<div>
  <%= link_to "Edit this patient", edit_patient_path(@patient) %> |
  <%= link_to "Back to patients", patients_path %>

  <%= button_to "Destroy this patient", @patient, method: :delete %>
</div>